Centos6Test:
  image: "centos:6"
  before_script:
    - rpm -i https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    - yum -y install ansible openssh-server openssh-client
    - service sshd start
    - echo localhost > inventory
  script:
    - ansible-playbook --syntax-check -i inventory test.yml
    - ansible-playbook -i inventory test.yml --connection=local -u root --become-user=root
UbuntuTest:
  image: "ubuntu:16.04"
  before_script:
    - apt-get update && apt-get -y install ansible openssh-server
    - echo localhost > inventory
  script:
    - ansible-playbook --syntax-check -i inventory test.yml
    - ansible-playbook -i inventory test.yml --connection=local -u root --become-user=root
