---
- hosts: all
  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    vbox_repo_url: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    vbox_repo_gpg_key: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
  tasks:
    - include: tasks/main.yml
