---
- hosts: all
  tasks:
    - include_tasks: tasks/main.yml
  vars:
    centos_repos:
      epel:
        name: EPEL
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        gpg_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        description: EPEL repository
    ubuntu_repos:
      virtualbox:
        name: VirtualBox
        url: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        gpg_key: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
      ansible:
        name: ansible
        url: 'ppa:ansible/ansible'
      docker:
        url: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
        keyserver: hkp://ha.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
