---
- hosts: all
  vars:
		centos_repos:
			epel:
				name: EPEL
				url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
				gpg_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
		ubuntu_repos:
			virtualbox:
				name: VirtualBox
				url: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
				gpg_key: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
  tasks:
    - include: tasks/main.yml
