---
- name: Add the repositories
  yum_repository:
    name: "{{ item.value.name }}"
    baseurl: "{{ item.value.url }}"
    file: "{{ item.key }}"
    gpgkey: "{{ item.value.gpg_key }}"
    state: present
  with_dict: "{{ centos_repos }}"
  when: centos_repos is defined
