---
- name: Add the repositories
  apt_repository:
    repo: "{{ item.value.url }}"
    state: present
    filename: "{{ item.key }}"
    mode: 644
  with_dict: "{{ ubuntu_repos }}"
  when: ubuntu_repos is defined

- name: Import the GPG keys
  apt_key:
    url: "{{ item.value.gpg_key }}"
    state: present
  with_dict: "{{ ubuntu_repos }}"
  when: ubuntu_repos is defined
