---
- name: Add the repositories
  apt_repository:
    repo: "{{ item.value.url }}"
    state: present
    mode: 644
  with_dict: "{{ ubuntu_repos }}"
  tags:
    - repos
  when: ubuntu_repos is defined

- name: Import the GPG keys
  apt_key:
    url: "{{ item.value.gpg_key }}"
    state: present
  with_dict: "{{ ubuntu_repos }}"
  tags:
    - repos
  when: (item.value.gpg_key is defined) and (ubuntu_repos is defined)
